---
title: "Data Analysis and Statistical Inference Lab 6 -  Linear regression"
author: "LKB"
output: 
  html_document: 
    highlight: tango
    theme: readable
---

```{r, echo=FALSE}
setwd("d:/tmp/Dropbox/Edu/Coursea/DataAnalysisAndStatisticalInference/")
rm(list=ls(all=TRUE))

library(knitr)
opts_chunk$set(echo = TRUE, cache = FALSE, cache.path = "cache/", fig.path = "figure/", warning = FALSE)
#http://yihui.name/knitr/options/
```

#Batter up


```{r}
load(url("http://www.openintro.org/stat/data/mlb11.RData"))

colnames(mlb11)
str(mlb11)
```

In addition to runs scored, there are seven traditionally used variables in the data set: at_bats, hits, homeruns, bat_avg (batting average), strikeouts, stolen_bases, and wins. Also see [Rules of baseball](https://en.wikipedia.org/wiki/Baseball_rules) and a [description of these statistics](, visit  and http://en.wikipedia.org/wiki/Baseball_statistics).


```{r}
plot(mlb11$runs,mlb11$bat_avg)
cor(mlb11$runs, mlb11$at_bats)
```

#Sum of squared residuals
